
from django_distill import distill_path  # type: ignore # Correct import for distill_path
from django.urls import reverse  # type: ignore # Import reverse from Django's core
from home import views
from django.views.generic.base import TemplateView  # type: ignore

# Usedistill_path for all URLs you want to generate statically
urlpatterns = [
   distill_path('', views.index, name='index'),
   distill_path('gallery/', views.gallery_view, name='gallery'),
   distill_path('about/', views.about_page, name='about'),
   distill_path('contact/', views.contact, name='contact'),
   distill_path('services/', views.services, name='services'),
   distill_path('seo/', views.seo, name='seo'),
   distill_path('thumbnails/', views.thumbnails, name='thumbnails'),
   distill_path('digitalmarketing/', views.digitalmarketing, name='digitalmarketing'),
  distill_path('german.html', views.german_view, name='german'),
   distill_path('other-topics.html', views.otherTopics, name='other_topics'),
   
    # Topic routes
   distill_path('nouns.html', views.nouns_view, name='nouns'),
   distill_path('articles.html', views.articles_view, name='articles'),
   distill_path('adjectives.html', views.adjectives_view, name='adjectives'),
   distill_path('conjugation.html', views.conjugation_view, name='conjugation'),
   distill_path('cases.html', views.cases_view, name='cases'),
   distill_path('prepositions.html', views.prepositions_view, name='prepositions'),
   distill_path('structure.html', views.structure_view, name='structure'),
   distill_path('listening.html', views.listening_view, name='listening'),
   distill_path('writing.html', views.writing_view, name='writing'),
   distill_path('speaking.html', views.speaking_view, name='speaking'),
   distill_path('culture.html', views.culture_view, name='culture'),
   distill_path('exam.html', views.exam_view, name='exam'),
   distill_path('personal-pronouns.html', views.personal_pronouns_view, name='personal-pronouns'),
   distill_path('verbs-wfrage-ja-nein-normaler.html', views.verbs_wfrage_ja_nein_normaler_view, name='verbs_wfrage_ja_nein_normaler'),
   distill_path('imperative.html', views.imperative_view, name='imperative'),
   distill_path('akkusative.html', views.akkusative_view, name='akkusative'),
   distill_path('possessive.html', views.possessive_view, name='possessive'),
   distill_path('modalverbpresent.html', views.modalverbpresent_view, name='modalverbpresent'),
   distill_path('praterituma1.html', views.praterituma1_view, name='praterituma1'),
   distill_path('trennbare.html', views.trennbare_view, name='trennbare'),
   distill_path('dative.html', views.dative_view, name='dative'),
   distill_path('wechsel.html', views.wechsel_view, name='wechsel'),
   distill_path('partizip2.html', views.partizip2_view, name='partizip2'),
   distill_path('welcherdieser.html', views.welcherdieser_view, name='welcherdieser'),
   distill_path('deshalbtrotzdem.html', views.deshalbtrotzdem_view, name='deshalbtrotzdem'),
   distill_path('a2-topics.html', views.a2topics_view, name='a2-topics'),
   distill_path('doch.html', views.doch_view, name='doch'),
   distill_path('reflexive.html', views.reflexive_view, name='reflexive'),
   distill_path('weil.html', views.weil_view, name='weil'),
   distill_path('modal_prateritum.html', views.modal_prateritum_view, name='modal_prateritum'),
   distill_path('dass.html', views.dass_view, name='dass'),
   distill_path('wenn.html', views.wenn_view, name='wenn'),
   distill_path('adjend.html', views.adjend_view, name='adjectiveending'),
   distill_path('comperlativesuperlative.html', views.comperlative_superlative_view, name='comperlativesuperlative'),
   distill_path('werden.html', views.werden_view, name='werden'),
   distill_path('indirect.html', views.indirect_view, name='indirect'),
   distill_path('konjunktiv2.html', views.konjunktiv2_view, name='konjunktiv2'),
   distill_path('genetivname.html', views.genetivname_view, name='genetivname'),
   distill_path('als.html', views.als_view, name='als'),
   distill_path('extrapronomen.html', views.extrapronomen_view, name='extrapronomen'),
   distill_path('Interrogativartikel.html', views.Interrogativartikel_view, name='Interrogativartikel'),
   distill_path('relativsatz.html', views.relativsatz_view, name='relativsatz'),
   distill_path('damitumzu.html', views.damitumzu_view, name='damitumzu'),
   distill_path('konjunktivII.html', views.konjunktivII_view, name='konjunktivII'),
   distill_path('verbenmitpreposition.html', views.verbenmitpreposition_view, name='verbenmitpreposition'),
   distill_path('wfrageprep.html', views.wfrageprep_view, name='wfrageprep'),  # Removed duplicates
   distill_path('b1-topics.html', views.b1_topics_view, name='b1-topic'),
   distill_path('infinitiv-zu.html', views.infinitiv_zu, name='infinitiv-zu'),
   distill_path('lassen.html', views.lassen, name='lassen'),
   distill_path('obwohl.html', views.obwohl, name='obwohl'),
   distill_path('genitiv.html', views.genitiv, name='genitiv'),
   distill_path('wegen-trotz.html', views.wegen_trotz, name='wegen-trotz'),
   distill_path('praeteritum.html', views.praeteritum, name='praeteritum'),
   distill_path('temp-praep.html', views.temp_praep, name='temp-praep'),
   distill_path('deshalb-darum.html', views.deshalb_darum, name='deshalb-darum'),
   distill_path('sodass.html', views.sodass, name='sodass'),
   distill_path('konj2.html', views.konj2, name='konj2'),
   distill_path('pronomen-praep.html', views.pronomen_praep, name='pronomen-praep'),
   distill_path('verben-praep.html', views.verben_praep, name='verben-praep'),
   distill_path('komp-super.html', views.komp_super, name='komp-super'),
   distill_path('aus-material.html', views.aus_material, name='aus-material'),
   distill_path('relativ-dativ.html', views.relativ_dativ, name='relativ-dativ'),
   distill_path('relativ-praep.html', views.relativ_praep, name='relativ-praep'),
   distill_path('plusquam.html', views.plusquam, name='plusquam'),
   distill_path('temp-neben.html', views.temp_neben, name='temp-neben'),
   distill_path('brauchen-zu.html', views.brauchen_zu, name='brauchen-zu'),
   distill_path('reflexiv.html', views.reflexiv, name='reflexiv'),
   distill_path('konnektoren.html', views.konnektoren, name='konnektoren'),
   distill_path('adj-ohne-art.html', views.adj_ohne_art, name='adj-ohne-art'),
   distill_path('passiv.html', views.passiv, name='passiv'),
   distill_path('passiv-modal.html', views.passiv_modal, name='passiv-modal'),
   distill_path('genitiv-praep.html', views.genitiv_praep, name='genitiv-praep'),
   distill_path('artikelpronomen.html', views.artikelpronomen, name='artikelpronomen'),
   distill_path('relativ-was-wo.html', views.relativ_was_wo, name='relativ-was-wo'),
   distill_path('je-desto.html', views.je_desto, name='je-desto'),
   distill_path('partizip-adj.html', views.partizip_adj, name='partizip-adj'),
   distill_path('n-dekl.html', views.n_dekl, name='n-dekl'),
   distill_path('exam1.html', views.exam1, name='exam1'),
   distill_path('exam2.html', views.exam2, name='exam2'),
   distill_path('exam3.html', views.exam3, name='exam3'),
   distill_path('exam4.html', views.exam4, name='exam4'),
   distill_path('exam5.html', views.exam5, name='exam5'),
   distill_path('exam6.html', views.exam6, name='exam6'),
   distill_path('exam7.html', views.exam7, name='exam7'),
   distill_path('exam8.html', views.exam8, name='exam8'),
   distill_path('exam9.html', views.exam9, name='exam9'),
   distill_path('exam10.html', views.exam10, name='exam10'),
   distill_path('schreibenb1.html', views.schreibenb1, name='schreibenb1'),
   distill_path('schreibenb1m2.html', views.schreibenb1m2, name='schreibenb1m2'),
   distill_path('schreibenb1m3.html', views.schreibenb1m3, name='schreibenb1m3'),
   distill_path('schreibenb1m4.html', views.schreibenb1m4, name='schreibenb1m4'),
   distill_path('schreibenb1m5.html', views.schreibenb1m5, name='schreibenb1m5'),
   distill_path('schreibenb1m6.html', views.schreibenb1m6, name='schreibenb1m6'),
   distill_path('schreibenb1m7.html', views.schreibenb1m7, name='schreibenb1m7'),
   distill_path('schreibenb1m8.html', views.schreibenb1m8, name='schreibenb1m8'),
   distill_path('schreibenb1m9.html', views.schreibenb1m9, name='schreibenb1m9'),
   distill_path('schreibenb1m10.html', views.schreibenb1m10, name='schreibenb1m10'),
   distill_path('practice_Exam.html', views.practiceExam, name='practice_Exam'),
   distill_path('sprechenb1m1.html', views.sprechenb1m1, name='sprechenb1m1'),
   distill_path('sprechenb1m2.html', views.sprechenb1m2, name='sprechenb1m2'),
   distill_path('sprechenb1m3.html', views.sprechenb1m3, name='sprechenb1m3'),
   distill_path('sprechenb1m4.html', views.sprechenb1m4, name='sprechenb1m4'),
   distill_path('sprechenb1m5.html', views.sprechenb1m5, name='sprechenb1m5'),
   distill_path('sprechenb1m6.html', views.sprechenb1m6, name='sprechenb1m6'),
   distill_path('sprechenb1m7.html', views.sprechenb1m7, name='sprechenb1m7'),
   distill_path('sprechenb1m8.html', views.sprechenb1m8, name='sprechenb1m8'),
   distill_path('sprechenb1m9.html', views.sprechenb1m9, name='sprechenb1m9'),
   distill_path('sprechenb1m10.html', views.sprechenb1m10, name='sprechenb1m10'),
]

def get_static_urls():
    # List all URLs for django-distill to process
    urls = [
        # From home/urls.py
        {'url': reverse('index'), 'params': {}},
        {'url': reverse('gallery'), 'params': {}},
        {'url': reverse('about'), 'params': {}},
        {'url': reverse('contact'), 'params': {}},
        {'url': reverse('services'), 'params': {}},
        {'url': reverse('seo'), 'params': {}},
        {'url': reverse('thumbnails'), 'params': {}},
        {'url': reverse('digitalmarketing'), 'params': {}},
        {'url': reverse('search'), 'params': {'query': ''}},  # Default query for static rendering
        {'url': reverse('custom_admin'), 'params': {}},  # Note: Might need to handle auth
        {'url': reverse('german'), 'params': {}},
        {'url': reverse('other_topics'), 'params': {}},
        # Topic routes
        {'url': reverse('nouns'), 'params': {}},
        {'url': reverse('articles'), 'params': {}},
        {'url': reverse('adjectives'), 'params': {}},
        {'url': reverse('conjugation'), 'params': {}},
        {'url': reverse('cases'), 'params': {}},
        {'url': reverse('prepositions'), 'params': {}},
        {'url': reverse('structure'), 'params': {}},
        {'url': reverse('listening'), 'params': {}},
        {'url': reverse('writing'), 'params': {}},
        {'url': reverse('speaking'), 'params': {}},
        {'url': reverse('culture'), 'params': {}},
        {'url': reverse('exam'), 'params': {}},
        {'url': reverse('personal-pronouns'), 'params': {}},
        {'url': reverse('verbs_wfrage_ja_nein_normaler'), 'params': {}},
        {'url': reverse('imperative'), 'params': {}},
        {'url': reverse('akkusative'), 'params': {}},
        {'url': reverse('possessive'), 'params': {}},
        {'url': reverse('modalverbpresent'), 'params': {}},
        {'url': reverse('praterituma1'), 'params': {}},
        {'url': reverse('trennbare'), 'params': {}},
        {'url': reverse('dative'), 'params': {}},
        {'url': reverse('wechsel'), 'params': {}},
        {'url': reverse('partizip2'), 'params': {}},
        {'url': reverse('welcherdieser'), 'params': {}},
        {'url': reverse('deshalbtrotzdem'), 'params': {}},
        {'url': reverse('a2-topics'), 'params': {}},
        {'url': reverse('doch'), 'params': {}},
        {'url': reverse('reflexive'), 'params': {}},
        {'url': reverse('weil'), 'params': {}},
        {'url': reverse('modal_prateritum'), 'params': {}},
        {'url': reverse('dass'), 'params': {}},
        {'url': reverse('wenn'), 'params': {}},
        {'url': reverse('adjectiveending'), 'params': {}},
        {'url': reverse('comperlativesuperlative'), 'params': {}},
        {'url': reverse('werden'), 'params': {}},
        {'url': reverse('indirect'), 'params': {}},
        {'url': reverse('konjunktiv2'), 'params': {}},
        {'url': reverse('genetivname'), 'params': {}},
        {'url': reverse('als'), 'params': {}},
        {'url': reverse('extrapronomen'), 'params': {}},
        {'url': reverse('Interrogativartikel'), 'params': {}},
        {'url': reverse('relativsatz'), 'params': {}},
        {'url': reverse('damitumzu'), 'params': {}},
        {'url': reverse('konjunktivII'), 'params': {}},
        {'url': reverse('verbenmitpreposition'), 'params': {}},
        {'url': reverse('wfrageprep'), 'params': {}},  # Fixed duplicates
        {'url': reverse('b1-topic'), 'params': {}},
        {'url': reverse('infinitiv-zu'), 'params': {}},
        {'url': reverse('lassen'), 'params': {}},
        {'url': reverse('obwohl'), 'params': {}},
        {'url': reverse('genitiv'), 'params': {}},
        {'url': reverse('wegen-trotz'), 'params': {}},
        {'url': reverse('praeteritum'), 'params': {}},
        {'url': reverse('temp-praep'), 'params': {}},
        {'url': reverse('deshalb-darum'), 'params': {}},
        {'url': reverse('sodass'), 'params': {}},
        {'url': reverse('konj2'), 'params': {}},
        {'url': reverse('pronomen-praep'), 'params': {}},
        {'url': reverse('verben-praep'), 'params': {}},
        {'url': reverse('komp-super'), 'params': {}},
        {'url': reverse('aus-material'), 'params': {}},
        {'url': reverse('relativ-dativ'), 'params': {}},
        {'url': reverse('relativ-praep'), 'params': {}},
        {'url': reverse('plusquam'), 'params': {}},
        {'url': reverse('temp-neben'), 'params': {}},
        {'url': reverse('brauchen-zu'), 'params': {}},
        {'url': reverse('reflexiv'), 'params': {}},
        {'url': reverse('konnektoren'), 'params': {}},
        {'url': reverse('adj-ohne-art'), 'params': {}},
        {'url': reverse('passiv'), 'params': {}},
        {'url': reverse('passiv-modal'), 'params': {}},
        {'url': reverse('genitiv-praep'), 'params': {}},
        {'url': reverse('artikelpronomen'), 'params': {}},
        {'url': reverse('relativ-was-wo'), 'params': {}},
        {'url': reverse('je-desto'), 'params': {}},
        {'url': reverse('partizip-adj'), 'params': {}},
        {'url': reverse('n-dekl'), 'params': {}},
        {'url': reverse('exam1'), 'params': {}},
        {'url': reverse('exam2'), 'params': {}},
        {'url': reverse('exam3'), 'params': {}},
        {'url': reverse('exam4'), 'params': {}},
        {'url': reverse('exam5'), 'params': {}},
        {'url': reverse('exam6'), 'params': {}},
        {'url': reverse('exam7'), 'params': {}},
        {'url': reverse('exam8'), 'params': {}},
        {'url': reverse('exam9'), 'params': {}},
        {'url': reverse('exam10'), 'params': {}},
        {'url': reverse('schreibenb1'), 'params': {}},
        {'url': reverse('schreibenb1m2'), 'params': {}},
        {'url': reverse('schreibenb1m3'), 'params': {}},
        {'url': reverse('schreibenb1m4'), 'params': {}},
        {'url': reverse('schreibenb1m5'), 'params': {}},
        {'url': reverse('schreibenb1m6'), 'params': {}},
        {'url': reverse('schreibenb1m7'), 'params': {}},
        {'url': reverse('schreibenb1m8'), 'params': {}},
        {'url': reverse('schreibenb1m9'), 'params': {}},
        {'url': reverse('schreibenb1m10'), 'params': {}},
        {'url': reverse('practice_Exam'), 'params': {}},
        {'url': reverse('sprechenb1m1'), 'params': {}},
        {'url': reverse('sprechenb1m2'), 'params': {}},
        {'url': reverse('sprechenb1m3'), 'params': {}},
        {'url': reverse('sprechenb1m4'), 'params': {}},
        {'url': reverse('sprechenb1m5'), 'params': {}},
        {'url': reverse('sprechenb1m6'), 'params': {}},
        {'url': reverse('sprechenb1m7'), 'params': {}},
        {'url': reverse('sprechenb1m8'), 'params': {}},
        {'url': reverse('sprechenb1m9'), 'params': {}},
        {'url': reverse('sprechenb1m10'), 'params': {}},
    ]
    return urls